### ISSUE TITLE
question [run normal. without docker?]

### ISSUE THREAD

**Issue by mrc4tt** [lyon-esport/AdminAFK#11]
Hi,

Can this "AdminAFK" run as normal, without docker? ;)
Thank you.

**Comment by M0NsTeRRR** [comment]
Hello,

Of course you can run it without Docker ;)

-> https://github.com/lyon-esport/AdminAFK#standard-1

Best regards,

**Comment by mrc4tt** [comment]
Hello,

Got it mate! thanks! :D

Now waiting for access to developer. - why do SteamID API needs?

**Comment by M0NsTeRRR** [comment]
When i've writed this project (my first one, as you can see it's really dirty :D), i've never found how to translate every format of steam ID to steam ID64 because this endpoint accept only steam ID64 https://developer.valvesoftware.com/wiki/Steam_Web_API#GetPlayerBans_.28v1.29 it's why i've used steamID API.

From now documentation has been improved and i've writed this little script for a guy -> https://gist.github.com/M0NsTeRRR/fe4f638f61409845fce3ff8f8314bfa1

If I want to improve the project I must rebuild everything with a framework and I don't have a lot of time to do it because I'm focused on differents project.

I will continue to update this project when it needs (new map for veto, to fix bug etc...) but I will not rebuild this project. If you want to do it and to improve it feel free to do it with pull request :)

**Comment by mrc4tt** [comment]
Cool, cool.

Do it works with BO3? - I know eBot(self) doesn't support BO3, which is so sad. ;/

**Comment by M0NsTeRRR** [comment]
My system is build on top of eBot. It will help you to manage matchs faster than eBot.

This tools will help you to edit matchs, you can edit  Bo3 faster by providing only ID and maps but it will not replace eBot and this bugs.

Destro (that is my opinion) will never update it to fix it, he doesn't have time and eBot has been out for a while :/.

**Comment by mrc4tt** [comment]
Yeah, it will never be fixed! ;/ so sad.

but people are now using Get5 example.
I don't think, there is other plugins/web panel with BO3 (as an option)

**Comment by M0NsTeRRR** [comment]
Yes i've checked too and only options are eBot and Get5
